# default num_head = 2
criterions:
  PerformanceLoss:
    def_file: ./loss/AsymmetricLoss.py
    loss_params: {gamma_neg:4, gamma_pos:0, clip:0.05, disable_torch_grad_focal_loss:True}
    optim_params: null
    weight: 1.0
last: false
# apply incremental pca to remove main components
apply_ipca: false
num_components: 80
model_dir: null
tuning_memory: false
networks:
  feat_model:
    def_file: ./models/ResNet50Feature.py
    fix: false
    optim_params: {lr: 0.01, momentum: 0.9, weight_decay: 0.0005}
    scheduler_params: {coslr: false, warmup: false, endlr: 0.0, gamma: 0.1, step_size: 10}
    params: {dataset: MLT_coco, dropout: null, stage1_weights: false, use_fc: true}
shuffle: false
training_opt:
  backbone: resnet50
  batch_size: 64
  dataset: MLT_coco
  train_annatation_path: /hdd8//dataset/coco/LT_Missing/30/LT_coco_train.json
  val_annatation_path: /hdd8//dataset/coco/annotations/LT_coco_val.json
  train_data_path: /hdd8//dataset/coco/LT_coco/
  val_data_path: /hdd8//dataset/coco/images/val2017/
  display_step: 10
  display_grad: False
  display_grad_step: 10
  feature_dim: 80
  log_dir: /home//project/ASL/log/coco/models/resnet50/
  log_root: /home//project/ASL/log/coco/
  num_classes: 80
  num_epochs: 30
  num_workers: 8
  open_threshold: 0.1
  sampler: null
  sub_dir: models
  gamma: 2
  gpu_ids: 0
