# default num_head = 2
criterions:
  PerformanceLoss:
    def_file: ./loss/SoftmaxLoss.py
    loss_params: {}
    optim_params: null
    weight: 1.0
last: false
# apply incremental pca to remove main components
apply_ipca: false
num_components: 512
model_dir: null
tuning_memory: false
networks:
  classifier:
    def_file: ./models/CausalNormClassifier.py
    optim_params: {lr: 0.1, momentum: 0.9, weight_decay: 0.0005}
    scheduler_params: {coslr: false, warmup: false, endlr: 0.0, gamma: 0.1, step_size: 10}
    params: {dataset: MLT_coco, feat_dim: 512, num_classes: 365, stage1_weights: false, use_effect: true, num_head: 1, tau: 16.0, alpha: 2, gamma: 0.03125}
  feat_model:
    def_file: ./models/ResNet50Feature.py
    fix: false
    optim_params: {lr: 0.01, momentum: 0.9, weight_decay: 0.0005}
    scheduler_params: {coslr: false, warmup: false, endlr: 0.0, gamma: 0.1, step_size: 10}
    params: {dataset: MLT_coco, dropout: null, stage1_weights: false, use_fc: true}
shuffle: false
training_opt:
  backbone: resnet50
  batch_size: 32
  dataset: MLT_coco
  train_annatation_path: /hdd8//dataset/coco/LT_Missing/50/LT_coco_train.json
  val_annatation_path: /hdd8//dataset/voc2012/annotation/LT_voc_test.json
  train_data_path: /hdd8//dataset/voc2012/VOCdevkit/VOC2012/JPEGImages/
  val_data_path: /hdd8//dataset/voc2007/VOCdevkit/VOC2007/JPEGImages/
  display_step: 10
  display_grad: False
  display_grad_step: 10
  feature_dim: 512
  log_dir: /home//project/ASL/log/coco/models/resnet50/
  log_root: /home//project/ASL/log/coco/
  num_classes: 80
  head_class_number: 200
  tail_class_number: 50
  num_epochs: 80
  num_workers: 8
  open_threshold: 0.1
  sampler: null
  sub_dir: models
  gamma: 2
  gpu_ids: 0
